services:
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    env_file:
      - path: .env.local
        required: false
    environment:
      - NODE_ENV=development

  prod:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - path: .env.local
        required: false
